In [19]:
from pathlib import Path
import pandas as pd

CHEMIN = Path("../data/raw/prenoms-2025-nat.csv")

In [4]:
with open(CHEMIN, encoding="UTF-8") as f :
    for _ in range(4) :
        print(repr(f.readline()))

'sexe;prenom;periode;valeur;rang\n'
'1;GABRIEL;2025;4625;1\n'
'1;NOAH;2025;3465;2\n'
'1;LÉO;2025;3420;3\n'

In [6]:
df = pd.read_csv(CHEMIN, sep=";", encoding="UTF-8")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 724645 entries, 0 to 724644
Data columns (total 5 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   sexe     724645 non-null  int64
 1   prenom   724644 non-null  str
 2   periode  724645 non-null  int64
 3   valeur   724645 non-null  int64
 4   rang     724645 non-null  int64
dtypes: int64(4), str(1)
memory usage: 32.3 MB

In [ ]:
# isna() pose la question « cette case est-elle vide ? » pour chaque ligne et répond Vrai ou Faux.
df[df["prenom"].isna()]

Empty DataFrame
Columns: [sexe, prenom, periode, valeur, rang]
Index: []

In [9]:
df = pd.read_csv(CHEMIN, sep=";", encoding="UTF-8", keep_default_na=False)
print(df["prenom"].isna().sum())
df[df["prenom"] == "NA"]

0

        sexe prenom  periode  valeur  rang
319660     2     NA     2003       5  5405

In [ ]:
print(df["periode"].min(), df["periode"].max(), df["periode"].nunique())
print(df["sexe"].value_counts())
# Le but : vérifier que toutes les valeurs sont des multiples de 5, comme l’INSEE l’annonce.
# On cherche des valeurs « louches ».
print(df["valeur"].min(), (df["valeur"] % 5 != 0).sum())
#.mean() fait la moyenne. Vrai compte 1 et Faux compte 0
print((df["valeur"] == 5).mean())

1900 2025 126
sexe
2    392962
1    331683
Name: count, dtype: int64
5 0
0.5149707787951342

In [13]:
totaux = df.groupby(["periode", "sexe"])["valeur"].sum().unstack()
totaux.loc[[1900, 1950, 2000, 2025]]

sexe          1       2
periode
1900     176390  236320
1950     451305  430345
2000     399880  377415
2025     302690  286795

In [ ]:
# But. Répondre à : « si un prénom n’a pas de ligne une année, a-t-il été donné 0 fois ? »
# La réponse est non.
g = df.groupby(["sexe", "prenom"])["periode"].agg(["min", "max", "count"])
g["span"] = g["max"] - g["min"] + 1
print((g["span"] != g["count"]).sum(), "sur", len(g))
# le prénoms qui ont des trous

34097 sur 52340

In [24]:
df[(df["prenom"] == "GABRIEL") & (df["periode"] == 1900)]

        sexe   prenom  periode  valeur  rang
722943     1  GABRIEL     1900    1300    32
724523     2  GABRIEL     1900       5   878

In [32]:
total_sexe_annee = df.groupby(["periode", "sexe"])["valeur"].transform("sum")
df["part_pour_10000"] = df["valeur"] / total_sexe_annee * 10000
df[(df["prenom"] == "MARIE") & (df["sexe"] == 2) & (df["periode"] == 1915)]

        sexe prenom  periode  valeur  rang  part_pour_10000
695230     2  MARIE     1915   26730     1       1474.88068

In [33]:
import pandas as pd

mini = pd.DataFrame({
    "prenom":     ["MARIE", "MARIE", "MARIE", "LOUISE", "LOUISE", "MARIE"],
    "sexe":       [2,       2,       2,       2,        2,        1],
    "annee":      [2020,    2021,    2023,    2020,     2021,     2020],
    "naissances": [50,      40,      30,      20,       25,       5],
})
mini

   prenom  sexe  annee  naissances
0   MARIE     2   2020          50
1   MARIE     2   2021          40
2   MARIE     2   2023          30
3  LOUISE     2   2020          20
4  LOUISE     2   2021          25
5   MARIE     1   2020           5

In [34]:
mini["prenom"] == "MARIE"

0     True
1     True
2     True
3    False
4    False
5     True
Name: prenom, dtype: bool

In [35]:
mini[mini["prenom"] == "MARIE"]

  prenom  sexe  annee  naissances
0  MARIE     2   2020          50
1  MARIE     2   2021          40
2  MARIE     2   2023          30
5  MARIE     1   2020           5

In [39]:
mini[(mini["prenom"] == "MARIE") & (mini["sexe"] == 2)]

  prenom  sexe  annee  naissances
0  MARIE     2   2020          50
1  MARIE     2   2021          40
2  MARIE     2   2023          30

In [40]:
selection = mini[(mini["prenom"] == "MARIE") & (mini["sexe"] == 2)]
selection.set_index("annee")[["naissances"]]

       naissances
annee
2020           50
2021           40
2023           30

In [41]:
selection.set_index("annee")[["naissances"]].reindex(range(2020, 2024))

       naissances
annee
2020         50.0
2021         40.0
2022          NaN
2023         30.0

In [42]:
"marie".upper()

'MARIE'

In [43]:
vide = mini[(mini["prenom"] == "ZZZ") & (mini["sexe"] == 2)]
vide.empty

True